from enum import Enum

class IntentType(str, Enum):

    INTERESTED = "INTERESTED"

    CONFUSED = "CONFUSED"

    ANGRY = "ANGRY"

    SPAM = "SPAM"

    HIGH_TICKET = "HIGH_TICKET"

    CALLBACK = "CALLBACK"

    EMI_QUERY = "EMI_QUERY"

    DOCUMENT_QUERY = "DOCUMENT_QUERY"

    UNKNOWN = "UNKNOWN"
    
    ESCALATION_REQUEST = "ESCALATION_REQUEST"
    
    CALL_END = "CALL_END"


class ConversationState(str, Enum):

    GREETING = "GREETING"

    ELIGIBILITY = "ELIGIBILITY"

    EMI_QUERY = "EMI_QUERY"

    DOCUMENT_REMINDER = "DOCUMENT_REMINDER"

    OBJECTION_HANDLING = "OBJECTION_HANDLING"

    CALLBACK_BOOKING = "CALLBACK_BOOKING"

    ESCALATION = "ESCALATION"

    CALL_END = "CALL_END"

MIN_AUDIO_CHUNK_SIZE = 100

AUDIO_LOG_INTERVAL = 200

DEBUG_AUDIO_ACKS = False